# This is an optional file for Tradeovate API credentials.
# If you use Tradeovate, populate this file like the example below
# and ensure it is added to your .gitignore if you commit your project.
#
# Example structure:
# tradeovate:
#   tradeovate_user: "YOUR_TRADEOVATE_USERNAME"
#   tradeovate_pass: "YOUR_TRADEOVATE_PASSWORD"
#   tradeovate_app_id: "YOUR_TRADEOVATE_APP_ID_OR_KEY" # e.g., "SampleApp" or a specific key
#   tradeovate_cid: 12345 # Your Customer ID (integer)
#   tradeovate_env: "demo" # "demo" or "live"
#
# The config_loader.py will merge these into the main configuration under 'api_keys'.
# For example, config.get('api_keys.tradeovate_user')
#
# If this file is empty or not present, the bot will operate without
# Tradeovate credentials, which is fine for backtesting or using other brokers.
